name: secondary-workflow
on: push
jobs:
    Linting:
        runs-on: ubuntu-latest
        steps:
            - name: Get code from Repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
              
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Get code from Repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test
    Building:
        runs-on: ubuntu-latest
        steps:
            - name: Get code from Repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Deploying the Code..."
